### ISSUE TITLE
[Suggestion] DST

### ISSUE THREAD

**Issue by ExpertNugget** [TheCommieAxolotl/BetterDiscord-Stuff#44]
### Addon

Timezones

### What happened?

Ability to set a start and end date for DST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FearNaBoinne** [comment]
I wanted to suggest this as well... 

DST is (unfortunately) still a major thing in a large part of the world. 

Most OSs will allow you to pull current local DST state, but DST dates and offsets unfortunately vary across the world. You'd probably need to import the TZDATA file and use the generic naming conventions (ie 'CET', 'EST' and 'America/Chicago' or 'Europe/Amsterdam') instead of just hours and minutes...

**Comment by FearNaBoinne** [comment]
This could be part of #20 and do it all at once...

**Comment by sophia1000** [comment]
there are only 13 different regions that do dst could just hardcode their times and have a dst dropdown to pick one if its a region that has dst. would be alot simpler yet still get the function across. https://en.wikipedia.org/wiki/Daylight_saving_time_by_country

**Comment by TheCommieAxolotl** [comment]
the Intl API now handles this in 1.1.0, dependent on your discord locale.
